# permissions for end users to edit indexstatemanagementpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indexstatemanagementpolicy-editor-role
rules:
- apiGroups:
  - opensearch.sputnik.systems
  resources:
  - indexstatemanagementpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.sputnik.systems
  resources:
  - indexstatemanagementpolicies/status
  verbs:
  - get
