# permissions for end users to view nodegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodegroup-viewer-role
rules:
- apiGroups:
  - opensearch.sputnik.systems
  resources:
  - nodegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opensearch.sputnik.systems
  resources:
  - nodegroups/status
  verbs:
  - get
